### ISSUE TITLE
Need help with providing power to disk enclosure in UGLY NAS

### ISSUE THREAD

**Issue by lambscaped** [fenio/ugly-nas#1]
I've been working on building my own NAS using your project as a guide and I really like it! However, I'm having trouble figuring out how to provide power to the disk enclosure through the odroid H3+. I was hoping you could help me by letting me know what physical components you used and how you made it work.

Thank you for your contribution to the community, and I look forward to hearing back from you!

Best regards,
Sergio Leyva

**Comment by fenio** [comment]
Hey @lambscaped 

Thanks for your report and yeah I should probably spend some time to update description to include final list of components.
Basically you just need two relatively cheap splitters in addition to what's listed.

I bought them on Allegro (let's call it Polish equivalent of Ebay).
[https://allegro.pl/oferta/kabel-zasilajacy-sata-podwojny-15cm-gembird-10973469194](SATA)
[https://allegro.pl/oferta/przejsciowka-kabel-sata-na-molex-15cm-lanberg-12481969887](Molex)

I found them also on Amazon but they are like 4x more expensive there:
[https://amzn.eu/d/5TaBAqU](SATA)
[https://amzn.eu/d/3ip2pUE](MOLEX)

Hope that helps.

**Comment by lambscaped** [comment]
Thanks a lot for the quick response and again for sharing with the
community i already bought the cable splitters threw aliexpress;

Have a nice spring day in Poland

**Comment by fenio** [comment]
Can you share a links to Aliexpress?
I will update the list ;)

**Comment by lambscaped** [comment]
Sure, here it is.
 € 1,45 | SATA II Hard Disk Power 15Pin SATA Male To 2 Female 15Pin Power
HDD Splitter High Quality Y 1 To 2 Extension Cable 20CM
https://a.aliexpress.com/_msgWjGs

€ 0,78 | SATA Power Extension Cable Serial ATA 15pin Male To Molex IDE 4pin
Female Power Supply For HDD Hard Disk Hard Drive
https://a.aliexpress.com/_msdB8kM

**Comment by fenio** [comment]
Thanks a lot. I've updated list of needed components thus I'm closing this issue ;)

**Comment by nettnikl** [comment]
Hey, i bought these, and it seems you need a SATA splitter + SATA Male To __2x__ Molex - the one linked here only has one Molex - does the cooler of the bay work with only one Molex connected to power? What are you supposed to connect? On the images sadly the cables are mostly hidden, and only the only one showing the cables (IMG_0889.jpeg) - has the black edge exactly in front of the relevant parts.

**Comment by fenio** [comment]
@nettnikl whole bay is powered in kinda weird way. One molex powers 4 disks and the other one remaining 2 of them.
Not sure which one powers fan as well since I removed it as it was too loud and I think in case of SSDs it's not so important. My setup (the one I use in real) in not really optimal since initially my plan was to power bay externally. Then I realized that there's enough power in Odroid itself so I took power from it but at the same time I wanted to reuse wires I already had. But if I recall correctly despite me having not optimal wiring I updated list that someone else could have optimal one. I'm not sure though since it was few months ago.

**Comment by nettnikl** [comment]
@fenio Your answer is much appreciated, thanks! Okay, so i understand your reasoning. Looking at my situation though, i'm still a bit unsure.. Maybe, sorry if asking too much, could you take a photo of your cables? Even if, as mentioned, sub- optimal, i'd be helpful to see a working setup.

**Comment by fenio** [comment]
@nettnikl I was in a good mood today and specially for you grabbed it from my lab shelf ;)

![IMG_1529](https://github.com/fenio/ugly-nas/assets/164051/f914d27f-8128-42b7-bcbe-a1149dbb1024)
![IMG_1530](https://github.com/fenio/ugly-nas/assets/164051/e29b8ce2-e7b9-4525-a783-c3344e2047f0)
![IMG_1531](https://github.com/fenio/ugly-nas/assets/164051/d7587807-90cd-454d-9917-021a0aca6151)

**Comment by fenio** [comment]
@nettnikl 
But in order to make it optimal at least from power usage perspective so 4 disks on one power output and 4 disks on another one you would have to do it this way:

* 1st output from Odroid

Mini 4-pin (2.54mm pitch) to SATA 15-pin
https://www.hardkernel.com/shop/sata-data-and-power-cable/

Then split it with SATA splitter:
https://pl.aliexpress.com/item/10000330531380.html

So now you've got two SATA

One SATA 15-pin to MOLEX - to power 2 disks from enclosure
https://pl.aliexpress.com/item/1005001338498358.html

And the other SATA needs to be split again with 
https://pl.aliexpress.com/item/10000330531380.html
to power two disks which are outside of enclosure.

* 2nd output from Odroid

We're starting again with
Mini 4-pin (2.54mm pitch) to SATA 15-pin
https://www.hardkernel.com/shop/sata-data-and-power-cable/
to have regular SATA

Then just conversion to MOLEX with:
https://pl.aliexpress.com/item/1005001338498358.html

Obviously if you find wire which converts Mini 4-pin straight to the MOLEX then you can skip SATA part.

Hope that helps.

**Comment by nettnikl** [comment]
Thank you so much! Yeah, you bet it helps!

**Comment by nettnikl** [comment]
PSA:
It seems in my case, the upper molex powers the fan and the upper 4 disks, the lower molex the lower 2 disks.
I'm now trying to distribute the power otherwise, with 
- mini sata power output 1
  -> to sata power
  -> to to molex
  - to upper case input
    -> to case fan
    -> to disk 1
    -> to disk 2
    -> to disk 3
    -> to disk 4
- mini sata power output 2
  -> to sata power
  -> to splitter
  - to lower case input
    -> to disk 5
    -> to disk 6
  - to second splitter
    -> to disk 7 (not in 6x case)
    -> to disk 8 (not in 6x case)

**Comment by fenio** [comment]
If I'm reading it correctly then it's more or less the same setup I described just with different order. In my case 2nd output for used to power 4 disks in enclosure and you did it with 1st output.
Anyway I'm glad that you made it working ;)
