### ISSUE TITLE
2x 4-bay enclosure

### ISSUE THREAD

**Issue by larseggert** [fenio/ugly-nas#2]
Thanks for the build writeup! Sorry, some hopefully easy questions:

I'm wondering if there are any upsides/downsides to using two [4-bay enclosures](https://www.aliexpress.com/item/1005004857864989.html?algo_pvid=7af35c8b-f3bc-4583-af24-74bba40b6cd3&algo_exp_id=7af35c8b-f3bc-4583-af24-74bba40b6cd3-52&pdp_ext_f=%7B%22sku_id%22%3A%2212000030773070520%22%7D&pdp_npi=3%40dis%21EUR%2152.8%2139.59%21%21%21%21%21%40211bf2da16805917388166777d070e%2112000030773070520%21sea%21FI%210&curPageLogUid=yFsEy6mL4inP) for the eight disks, rather than your current build? 

Also, for the [Case Type 5](https://www.hardkernel.com/shop/odroid-h3-case-type-5/), it says "Net card is necessary to assemble this case", but your build does not seem to include that? Would a [Case Type 3](https://www.hardkernel.com/shop/odroid-h3-case-type-3/) work to contain two SSDs, and then the other six would go into the 6-bay enclosure from your build list?

**Comment by fenio** [comment]
Hey @larseggert 

So the reason I haven''t decided to use 8 bays or 2x4 bays enclosure(s) is because Odroid doesn't support hotplug for the drives directly attached to it. So while technically you can of course ignore that fact and put all the drives into enclosures then you'll be at risk of damaging Odroid by removing one of these two disks during work. I wanted to avoid that risk.

I mentioned it also in the [writeup](https://github.com/fenio/ugly-nas#why-are-two-disks-directly-plugged-into-odroid-not-part-of-enclosure)


Speaking about cases - type 5 vs type 3 - to be honest I left case on the listing mostly because in the end I used some parts (supports, fan) from it but as you can see on the pictures my case is DIY solution and you you buy supports, fan separately then you don't really need case from Odroid. I chose type 5 case at the beginning cause initial vision was slightly different from what I did at the end. After all whole solution was evolving and I tried several approaches.

**Comment by larseggert** [comment]
Ah, got it. I wouldn't do any hotplugging anyway, so I guess an eight-bay would work - do you know if the company that makes the six-bay one has one? Wasn't able to find on AliExpress.

I'll just get the smallest case then, if all my drives go into an enclosure.

Do you see any benefit in getting the slightly more powerful power adaptor? It seems like the one you included it your build should be sufficient though.

Thanks for the answers!

**Comment by fenio** [comment]
I guess the reason they do just 6-bays is because of its dimensions. It's meant to be put in 5,25" aka CDROM/DVD bay in PC. Not sure if they do also 8-bay versions.

Speaking about power adaptor. Again it my case the setup is made this way since initially I wasn't even sure if I can use just PSU attached to Odroid. Initially I wanted to power enclosure separately. But then I made some measurements and it turned out that power from Odroid itself should be enough. I'm also not using any additional stuff connected to USB and so on and *just* SSD disks. If you're planning to use more peripherials or different disks then maybe it makes sense to get more powerful adaptor.

**Comment by larseggert** [comment]
Thanks! 

I ordered the largest case and no drive enclosure - will just keep the drives in there...

Will update you how my build goes once parts arrive.

**Comment by fenio** [comment]
Good luck!
I though my NAS is ugly but apparently you want to take that title from me ;)

**Comment by fenio** [comment]
How did it go? ;)

**Comment by larseggert** [comment]
Has been working great!

**Comment by fenio** [comment]
Glad to hear that! Congratulations ;)
Does it mean that the issue has been solved and I can close it? :)

**Comment by larseggert** [comment]
Oh, yes!
